/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.ControllerInterface;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;


/**
 *
 * @author Anders
 */
public class SearchFreeRoomsDiffDates extends javax.swing.JFrame
{
    JFrame fr6;
    ControllerInterface conIf;
    DefaultListModel model1;

    /**
     * Creates new form SearchFreeRoomsDiffDates
     */
    public SearchFreeRoomsDiffDates(ControllerInterface c, JFrame fr6)
    {
        initComponents();
        model1 = new DefaultListModel();
        this.fr6 = fr6;
        conIf = c;
        jList1.setModel(model1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jBCheck = new javax.swing.JButton();
        jTFStartDate = new javax.swing.JTextField();
        jTFEndDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jBCheck.setText("Check");
        jBCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBCheckActionPerformed(evt);
            }
        });

        jTFStartDate.setText("jTextField1");
        jTFStartDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTFStartDateActionPerformed(evt);
            }
        });

        jTFEndDate.setText("jTextField2");
        jTFEndDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTFEndDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBCheck))
                    .addComponent(jTFStartDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCheck))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBCheckActionPerformed
    {//GEN-HEADEREND:event_jBCheckActionPerformed
        Date enddate = null;
        Date startdate = null; 
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateSta = (jTFStartDate.getText());
        try { 
            startdate = formatter.parse(dateSta); }
        catch (ParseException e) {
            jTFStartDate.setText("Error in Start date");
        }
        SimpleDateFormat formatter2 = new SimpleDateFormat("dd/MM/yyyy");
        String dateEnd = (jTFEndDate.getText());
        try { 
            enddate = formatter2.parse(dateEnd); }
        catch (ParseException e) {
            jTFEndDate.setText("Error in End date");
        }
        
                try
            {
                int[] searchresults = conIf.searchForFreeRoomsAtDiffDates(startdate, enddate);
                for (int i=0;i<searchresults.length;i++){
                    model1.addElement(conIf.searchForFreeRoomsAtDiffDates(enddate, startdate));
                }
            } 
               catch (SQLException ex)
            {
                jTFStartDate.setText("Error in Start date");
                jTFEndDate.setText("Error in End date");
            }
            
        
    }//GEN-LAST:event_jBCheckActionPerformed

    private void jTFStartDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTFStartDateActionPerformed
    {//GEN-HEADEREND:event_jTFStartDateActionPerformed
        jTFStartDate.setText("Indtast Start dato");
    }//GEN-LAST:event_jTFStartDateActionPerformed

    private void jTFEndDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTFEndDateActionPerformed
    {//GEN-HEADEREND:event_jTFEndDateActionPerformed
        jTFEndDate.setText("Indtast slut dato");
    }//GEN-LAST:event_jTFEndDateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCheck;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFEndDate;
    private javax.swing.JTextField jTFStartDate;
    // End of variables declaration//GEN-END:variables
}
